# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-22.04

    environment:
      name: LLMsWebScraper
      url: https://pypi.org/project/LLMsWebScraper/

    permissions:
      id-token: ${{ secrets.PYPI_API_KEY }}  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
   
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      run: |
        git fetch --all --tags
        python setup.py sdist bdist_wheel
        twine upload dist/*
    
